#!/usr/bin/env python3
"""Bench runner.

Executes the invariant scenarios and the topology comparison, then writes
results as JSON and Markdown.

Usage:
    python3 bench.py              # invariants + comparison
    python3 bench.py --invariants # mechanism tests only (fast)
    python3 bench.py --compare    # topology comparison only
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from providers.base import get as get_provider          # noqa: E402
from scenarios.run import (ScenarioResult, compare_topologies,  # noqa: E402
                           invariant_concurrent, invariant_kill,
                           invariant_lease, invariant_lexical_guard,
                           invariant_version_pin)
from worklist import Worklist                            # noqa: E402

OUT = Path(__file__).parent / "results"


def _fresh_db(tag: str) -> str:
    p = Path(f"/tmp/bench_{tag}_{int(time.time() * 1000)}.db")
    if p.exists():
        p.unlink()
    return str(p)


def run_invariants(provider) -> list[ScenarioResult]:
    results: list[ScenarioResult] = []

    print("  ownership survives SIGKILL ...", flush=True)
    results.append(invariant_kill(_fresh_db("kill")))
    print("    ->", results[-1].passed, "|", results[-1].detail)

    print("  expired lease becomes restartable ...", flush=True)
    results.append(invariant_lease(_fresh_db("lease")))
    print("    ->", results[-1].passed, "|", results[-1].detail)

    print("  concurrent claim exclusivity ...", flush=True)
    results.append(invariant_concurrent(_fresh_db("race")))
    print("    ->", results[-1].passed, "|", results[-1].detail)

    print("  version pinning holds ...", flush=True)
    results.append(invariant_version_pin(_fresh_db("pin")))
    print("    ->", results[-1].passed, "|", results[-1].detail)

    print("  lexical guard vs prose rule (uses API) ...", flush=True)
    results.append(invariant_lexical_guard(provider, _fresh_db("guard")))
    print("    ->", results[-1].passed, "|", results[-1].detail)

    # Cross-provider refuter cannot run with a single provider configured.
    results.append(ScenarioResult(
        name="invariant: refuter on a different provider",
        passed=False, not_run=True,
        detail=("NOT RUN: only one provider is configured (deepseek). The "
                "cross-provider invariant requires a second provider; a "
                "same-provider comparison would not test it."),
    ))
    return results


def run_compare(provider, n: int) -> dict:
    out = {}
    for topo in ("hub", "relay"):
        print(f"  topology={topo} ({n} tasks) ...", flush=True)
        out[topo] = compare_topologies(provider, topo, n=n)
        m = out[topo]
        print(f"    fidelity {m['fidelity_hits']}/{m['tasks']} | "
              f"parent_prompt={m['parent_prompt_tokens']} "
              f"child_prompt={m['child_prompt_tokens']} "
              f"child_share={m['child_share']:.2f} | calls={m['provider_calls']}")
    return out


def write_reports(invariants: list[ScenarioResult], comparison: dict | None,
                  provider_name: str) -> None:
    OUT.mkdir(exist_ok=True)
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")

    payload = {
        "ran_at": stamp,
        "provider": provider_name,
        "invariants": [
            {"name": r.name, "passed": r.passed, "not_run": r.not_run,
             "detail": r.detail, "metrics": r.metrics} for r in invariants
        ],
        "comparison": comparison,
    }
    (OUT / "results.json").write_text(json.dumps(payload, indent=2))

    lines = [
        "# Bench results",
        "",
        f"Ran {stamp}. Provider: `{provider_name}`.",
        "",
        "> Generated by `bench.py`. Numbers come from the provider's reported",
        "> usage, not local estimates.",
        "",
        "## Invariants",
        "",
        "| Invariant | Result | Detail |",
        "| --- | --- | --- |",
    ]
    for r in invariants:
        mark = "NOT RUN" if r.not_run else ("PASS" if r.passed else "FAIL")
        lines.append(f"| {r.name} | **{mark}** | {r.detail} |")

    if comparison:
        lines += [
            "",
            "## Hub vs relay",
            "",
            "Identical tasks and payload; the only difference is whether the",
            "specialist receives primary artifacts (hub) or the owner's paraphrase",
            "(relay). Fidelity counts how often a planted fact survived to the",
            "final output.",
            "",
            "| Metric | hub | relay |",
            "| --- | --- | --- |",
        ]
        keys = ["tasks", "fidelity_hits", "fidelity_rate", "parent_prompt_tokens",
                "child_prompt_tokens", "child_share", "total_prompt_tokens",
                "total_completion_tokens", "provider_calls", "seconds"]
        for k in keys:
            h = comparison.get("hub", {}).get(k)
            r = comparison.get("relay", {}).get(k)
            if isinstance(h, float):
                h = f"{h:.3f}"
            if isinstance(r, float):
                r = f"{r:.3f}"
            lines.append(f"| {k} | {h} | {r} |")

    lines += [
        "",
        "## Limits",
        "",
        "- One provider is configured, so the cross-provider refuter invariant is",
        "  NOT RUN. It is not approximated with a same-provider substitute.",
        "- The comparison is designed by the same author as the harness under test.",
        "  It is a mechanism check, not an independent benchmark.",
        "- Single-task runs cannot measure the concurrency claim. `child_share`",
        "  shows where tokens went, not whether the work was better.",
        "",
    ]
    (OUT / "RESULTS.md").write_text("\n".join(lines))
    print(f"\nwrote {OUT/'results.json'} and {OUT/'RESULTS.md'}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--provider", default="deepseek")
    ap.add_argument("--tasks", type=int, default=3)
    ap.add_argument("--invariants", action="store_true")
    ap.add_argument("--compare", action="store_true")
    args = ap.parse_args()

    do_inv = args.invariants or not args.compare
    do_cmp = args.compare or not args.invariants

    print(f"provider={args.provider}")
    provider = get_provider(args.provider)

    inv: list[ScenarioResult] = []
    cmp_result = None

    if do_inv:
        print("\n[invariants]")
        inv = run_invariants(provider)
    if do_cmp:
        print("\n[comparison]")
        cmp_result = run_compare(provider, args.tasks)

    write_reports(inv, cmp_result, args.provider)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
